import labData from "@/app/data/labProjects.json";

/**
 * The interactive charts hosted on this domain, as opposed to the Tableau work
 * in tableauProjects.json which is only linked to.
 *
 * Generated by a separate repo (charts/<slug>/ -> one flattened HTML file) and
 * dropped into public/viz/ verbatim. Nothing here parses them.
 */
export type LabProject = {
  slug: string;
  file: string;
  title: string;
  dek: string;
  method: string;
  /** The chart's own alias, from `queryParam` in its charts/<slug>/chart.js. */
  queryParam: string;
  /** What that alias selects, for prose: "country", "city". */
  subjectNoun: string;
  defaultSubject: string;
  examples: string[];
  /** A PNG exported from the chart's own Download PNG button, or null. */
  poster: string | null;
};

export const labProjects: LabProject[] = labData.projects;

export const labProjectBySlug = (slug: string | undefined): LabProject | undefined =>
  labProjects.find((project) => project.slug === slug);

/**
 * A direct link to the standalone page, optionally seeded with a subject.
 *
 * Passing the subject rather than relying on the value baked into the file is
 * what lets one 200KB bundle serve every country instead of one file each.
 *
 * These are real static files, not routes — always reach them with a plain
 * <a href>. A react-router <Link> would be intercepted and the "*" catch-all
 * in App.tsx would bounce it home.
 */
export const vizHref = (project: LabProject, subject?: string) =>
  subject
    ? `${project.file}?${project.queryParam}=${encodeURIComponent(subject)}`
    : project.file;
