import labData from "@/app/data/labProjects.json";

/**
 * The interactive charts hosted on this domain, as opposed to the Tableau work
 * in tableauProjects.json which lives at Tableau Public and is only linked to.
 *
 * These pages are generated by a separate repo (charts/<slug>/ -> one flattened
 * HTML file) and dropped into public/viz/ verbatim. Nothing here parses them;
 * this module only knows how to name them and how to address a subject.
 */
export type LabProject = {
  slug: string;
  file: string;
  title: string;
  dek: string;
  method: string;
  /** The chart's own alias, from `queryParam` in its charts/<slug>/chart.js. */
  queryParam: string;
  /** What that alias selects, for prose: "country", "city". */
  subjectNoun: string;
  defaultSubject: string;
  examples: string[];
  /** A PNG exported from the chart's own Download PNG button, or null. */
  poster: string | null;
};

export const labProjects: LabProject[] = labData.projects;

export const labSource = labData.source;

export const labProjectBySlug = (slug: string | undefined): LabProject | undefined =>
  labProjects.find((project) => project.slug === slug);

/**
 * A direct link to the standalone page, optionally seeded with a subject.
 *
 * Every chart's shell accepts ?subject=; each also answers to a friendlier
 * alias (?country=, ?city=) which is the form worth putting in front of a
 * reader. Passing the subject rather than relying on the value baked into the
 * file is what lets one 200KB bundle serve every country instead of one file
 * each — country-strips-japan.html was exactly this link, spelled as a build.
 *
 * Note these are real static files, not routes — they must always be reached
 * with a plain <a href>. A react-router <Link> would be intercepted, and the
 * "*" catch-all in App.tsx would bounce it to the home page.
 */
export const vizHref = (project: LabProject, subject?: string) =>
  subject
    ? `${project.file}?${project.queryParam}=${encodeURIComponent(subject)}`
    : project.file;
